name 'cookbook2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook2'
long_description 'Installs/Configures cookbook2'
version '0.1.0'
